name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['2.4', '2.5', '2.6', '2.7', '3.0']
        gemfile: ['gemfiles/rails_5.0.gemfile', 'gemfiles/rails_5.1.gemfile', 'gemfiles/rails_5.2.gemfile', 'gemfiles/rails_6.0.gemfile']
        exclude:
          - ruby: '2.4'
            gemfile: 'gemfiles/rails_6.0.gemfile'
          - ruby: '3.0'
            gemfile: 'gemfiles/rails_5.0.gemfile'
          - ruby: '3.0'
            gemfile: 'gemfiles/rails_5.1.gemfile'
          - ruby: '3.0'
            gemfile: 'gemfiles/rails_5.2.gemfile'
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    name: Ruby ${{ matrix.ruby }}, ${{ matrix.gemfile }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake spec
